---
title: "p8105_hw6_tl3195"
author: "Tingyi Li"
date: "2023-12-01"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# Problem 2

*Import the dataset 
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

*A simple linear regression with tmax as the response with tmin and prcp as the predictors
```{r}
boot_sample = function(df) {
  sample_frac(df, replace = TRUE)
}

boot_straps = 
  tibble(strap_number = 1:5000) |> 
  mutate(
    strap_sample = map(strap_number, \(i) boot_sample(df = weather_df)),
    models = map(strap_sample, \(df) lm(tmax ~ tmin + prcp, data=df)),
    r_squared = map(models, broom::glance),
    results = map(models, broom::tidy)
  )|>
  select(strap_number, r_squared, results)|>
  unnest(r_squared, results)|>
  select(strap_number, r.squared, term, estimate)|>
  pivot_wider(
    names_from = term,
    values_from = estimate
  )|>
  janitor::clean_names()|>
  mutate(
    logb = log(prcp * tmin)
  )|>
  select(strap_number, r_squared, logb)

boot_straps

```

*Plot the distribution of r_squared
```{r}
boot_straps|>
  ggplot(aes(x = r_squared)) +
  geom_density()
```

